name: eigendata-demo
channels:
 - defaults
 - fastai
 - conda-forge
dependencies:
 - jupyterhub=1.2.2
 - python=3.7
 - pandas=1.1.2
 - numpydoc=1.1.0 
 - fastcore=1.3.2
 - jupyterlab=3.2.1
 - nbconvert>=5.6.1
 - nbclassic=0.3.1
 - xlrd=1.2.0
 - rapidfuzz=1.4.1
 - missingno=0.4.2 
 - pip
 - pip:
    - fastdata
    - eigendata==0.3.5
    - airtable-python-wrapper
    - plotly==5.0.0