name: eigendata
channels:
 - defaults
 - fastai
 - conda-forge
dependencies:
 - python=3.7
 - pandas=1.1.2
 - numpydoc=1.1.0 
 - fastcore=1.3.2
 - nodejs>10.14.0
 - jupyterlab=2.2.6
 - numpy<1.19.4
 - xlrd>1.0.0
 - pip
 - pip:
    - fastdata
    - pyforest